version: "3.1"
services:
  homepage:
    restart: always
    build:
      context: "."
      dockerfile: ./Dockerfile
    image: homepage
    container_name: homepage
    ports:
      - 8800:80
    volumes:
      - /app/node_modules
      - .:/app
